auth_test.py::SubmissionTest::test_voting_down
--------------------------------------------------------------------
Last Page: http://127.0.0.1:8000/
  Browser: firefox (104.0.2)
   Driver: geckodriver (0.31.0)
Timestamp: 1663916151  (Unix Timestamp)
     Date: Thursday, September 22, 2022
     Time: 11:55:51 PM  (Pacific Daylight Time, UTC-08:00)
--------------------------------------------------------------------
Traceback: File "c:\python38-32\lib\unittest\case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "c:\python38-32\lib\unittest\case.py", line 633, in _callTestMethod
    method()
  File "C:\Users\Ian\Documents\Python Scripts\Bandnames\bandnames.cool\bnSubmission\tests\auth_test.py", line 98, in test_voting_down
    self.assert_text("Voted down", "#submission-status")
  File "c:\python38-32\lib\site-packages\seleniumbase\fixtures\base_case.py", line 10490, in assert_text
    self.wait_for_text_visible(text, selector, by=by, timeout=timeout)
  File "c:\python38-32\lib\site-packages\seleniumbase\fixtures\base_case.py", line 10415, in wait_for_text_visible
    return page_actions.wait_for_text_visible(
  File "c:\python38-32\lib\site-packages\seleniumbase\fixtures\page_actions.py", line 546, in wait_for_text_visible
    timeout_exception(TextNotVisibleException, message)
  File "c:\python38-32\lib\site-packages\seleniumbase\fixtures\page_actions.py", line 190, in timeout_exception
    raise exc(msg)
Exception: Message: 
 Expected text substring {Voted down} for {#submission-status} was not visible after 7 seconds!
